name: Publish to JSR

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: latest

      - run: deno publish
